PREPROCESSING:
  DATASET: FaceForensicsTest
  COMPRESSION: c0
  SPLIT: test
  ROOT: /content/LAA-Net/FaceForensicsTest/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  FAKETYPE: [YouTube-real]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
