PREPROCESSING:
  DATASET: FaceForensicsTest
  COMPRESSION: c0
  SPLIT: test
  ROOT: /https://drive.google.com/drive/folders/14YM3Zw62KXhAPesHhwGZ2PK7dBJHqddz?usp=drive_link/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  FAKETYPE: [YouTube-real]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
